# Define the orb
version: 2.1
description: Filters static files from a project
name: static-files-filter
namespace: nazehs

# Define the parameters that can be passed to the orb
parameters:
  executor:
    default: default
    type: executor
  filter:
    description: Filters static files
    parameters:
      when:
        type: object
        properties:
          changeset:
            type: changeset
            includes:
              type: array
              items:
                type: string
            excludes:
              type: array
              items:
                type: string
      filter-branch:
        type: object
        properties:
          only:
            type: array
            items:
              type: string
            default:
              - all

    steps:
      - filters:
          branches:
            only: << parameters.filter.filter-branch.only >>
            condition:
              and:
                includes: << parameters.filter.when.changeset.includes || defaults.changeset_includes >>
                excludes: << parameters.filter.when.changeset.excludes || defaults.changeset_excludes >>

# Define the jobs that can use the orb
jobs:
  filter:
    executor: << parameters.executor >>
    steps:
      - attach-workspace
      - when:
          <<: *when
          filters:
            branches:
              only: << parameters.filter.filter-branch.only >>

# Define the executors that can be used with the orb
executors:
  default:
    docker:
      - image: 'circleci/python:3.9.0'
