# Define the orb
version: 2.1
description: Filters static files from a project
name: filter-static-files
namespace: nazehs
# based on CircleCI parameters
when: &when
  when_changeset:
    includes: << parameters.when.when_changeset.includes || defaults.changeset_includes >>
    excludes: << parameters.when.when_changeset.excludes || defaults.changeset_excludes >>

filter-branch: &filter-branch
  branches:
    only: << parameters.filter.branches.only || defaults.branches >>
    when:
      changeset:
        includes: << parameters.filter.when.changeset.includes || defaults.changeset_includes >>
        excludes: << parameters.filter.when.changeset.excludes || defaults.changeset_excludes >>

# Define the commands in the orb
commands:
  filter:
    description: Filters static files
    parameters:
      when:
        type: object
        properties:
          changeset:
            type: object
            properties:
              includes:
                type: array
                items:
                  type: string
              excludes:
                type: array
                items:
                  type: string
      filter-branch:
        type: object
        properties:
          branches:
            type: object
            properties:
              only:
                type: array
                items:
                  type: string
    steps:
      - filters:
          <<: *filter-branch

# Define the parameters that can be passed to the orb
parameters:
  when:
    type: object
    properties:
      changeset:
        type: object
        properties:
          includes:
            type: array
            items:
              type: string
          excludes:
            type: array
            items:
              type: string
  filter-branch:
    type: object
    properties:
      branches:
        type: object
        properties:
          only:
            type: array
            items:
              type: string

# Define the jobs that can use the orb
jobs:
  filter:
    executor: filter-static-files/default
    steps:
      - filter:
          <<: *when
          # <<: *filter-branch

# Define the executors that can be used with the orb
executors:
  default:
    docker:
      - image: 'circleci/python:3.9.0'
